import type { Metadata } from "next";
import "./globals.css";
// import Header from './components/Header';
import Footer from './components/Footer';
import { BsListNested } from "react-icons/bs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Clash Display font via link */}
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@300,400,500,600,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-clash">
        {/* <Header /> */}
        <div className="text-xl bg-white px-6 py-2 fixed bottom-0 left-0 z-50 flex items-center justify-between gap-4">MENU <BsListNested /></div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
